name: "build"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '20 13 * * 2'

defaults:
  run:
    working-directory: ./pbiviz

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: ./dc.sh build pbi
    - name: lint
      run: ./bin/lint.sh
    - name: test
      run: ./bin/test.sh
    - name: bundle
      run: ./bin/package.sh
