name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+(.*)'

defaults:
  run:
    working-directory: ./pbiviz

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PBI_TEST_PUBLIC_CERTIFICATE: ${{ secrets.PBI_TEST_PUBLIC_CERTIFICATE }}
      PBI_TEST_PRIVATE_KEY: ${{ secrets.PBI_TEST_PRIVATE_KEY }}
      CERTS_PATH: ./certs
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get most recent tag
      run: |
        echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: check env
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: certs
      run: |
        mkdir -p certs
        echo "${PBI_TEST_PUBLIC_CERTIFICATE}" > certs/PowerBICustomVisualTest_public.crt
        echo "${PBI_TEST_PRIVATE_KEY}" > certs/PowerBICustomVisualTest_private.key
        touch certs/blank
    - name: build
      run: |
       ./dc.sh build pbi
       echo $VERSION
       echo “pwd: $(pwd)”
       echo "PWD=$(pwd)" >> $GITHUB_ENV
       echo ${{ env.pwd }}
    - name: lint
      run: ./bin/lint.sh
    - name: test
      run: ./bin/test.sh
    - name: bundle
      run: |
        echo $RELEASE_VERSION
        ./bin/package.sh
        echo "github.ref: ${{ github.ref }}"
        find ./dist
        echo “pwd: $(pwd)”
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.RELEASE_VERSION }}
        tag_name: ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
           /home/runner/work/graphbi/graphbi/pbiviz/dist/graphbi.${{ env.RELEASE_VERSION }}
           /home/runner/work/graphbi/graphbi/pbiviz/dist/Graphistry.${{ env.RELEASE_VERSION }}-8-g55e9eb2.pbiviz
